# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  ruby: circleci/ruby@1.8.0

default_environment: &default_environment
  RAILS_ENV: test
  RACK_ENV: test
  FCREPO_TEST_PORT: 8080
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
  SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
  COVERALLS_PARALLEL: true
  WD_INSTALL_DIR: ./webdriver
  KARMA_BROWSER: ChromeHeadless
  KARMA_HOSTNAME: localhost

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6-browsers
      - image: cimg/redis:6.2
      - image: ghcr.io/samvera/fcrepo4:4.7.5
        environment:
          CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
      - image: solr:7
        command: bin/solr -cloud -noprompt -f -p 8985
      - image: cimg/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: essi_test
          MYSQL_USER: essi
          MYSQL_PASSWORD: essi

    resource_class: medium+
    working_directory: ~/repo

    environment:
      <<: *default_environment

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout

      # BUNDLE_PATH is unset to allow for `bundle config path` to take precedence.
      - run:
          name: Extra environment setup
          command: |
            echo 'unset BUNDLE_PATH' >> $BASH_ENV

      - run:
          name: Install system deps
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get update -qq
            sudo apt-get install -y --no-install-recommends build-essential default-jre-headless libpq-dev nodejs \
                                    libreoffice-writer libreoffice-impress imagemagick unzip ghostscript \
                                    libtesseract-dev libleptonica-dev liblept5 tesseract-ocr \
                                    yarn libopenjp2-tools libxml2-dev libsqlite3-dev
            sudo mkdir -p -m 777 /opt/fits
            curl -fSL -o /tmp/fits-1.5.5.zip https://github.com/harvard-lts/fits/releases/download/1.5.5/fits-1.5.5.zip
            sudo mv /tmp/fits-1.5.5.zip /opt/fits
            cd /opt/fits && sudo unzip fits-1.5.5.zip && sudo chmod +X fits.sh
            sudo sed -i 's/\(<tool.*TikaTool.*>\)/<!--\1-->/' /opt/fits/xml/fits.xml
            echo 'export PATH=/opt/fits:$PATH' >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-v6-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - dependencies-v6-{{ .Branch }}
            - dependencies-v6-

      - run:
          name: Install dependencies
          command: |
            gem update --system
            gem update bundler
            bundle config path $CIRCLE_WORKING_DIRECTORY/vendor/bundle
            bundle install
            bundle pristine webdrivers
            bundle clean
            bundle exec rails webdrivers:chromedriver:update
            yarn

      - save_cache:
          paths:
            - ./public/uv
            - ./node_modules
            - ./vendor/bundle
            - ./webdriver
          key: dependencies-v6-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      #    - run:
      #        name: Call Rubocop
      #        command: bundle exec rubocop

#      - run:
#          name: Start headless Chrome
#          command: google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost
#          background: true

      - run:
          name: Load config into SolrCloud
          command: |
            cd solr/conf
            zip -1 -r solr_hyrax_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_hyrax_config.zip "http://localhost:8985/solr/admin/configs?action=UPLOAD&name=hyrax"
            curl -H 'Content-type: application/json' http://localhost:8985/api/collections/ -d '{create: {name: hydra-test, config: hyrax, numShards: 1}}'

      - ruby/rspec-test

      - store_artifacts:
          path: tmp/capybara
          destination: capybara-screenshots
